export enum QuestCodes {
  CHECK_IN = "KATK_1",
  VISIT_WEBSITE = "KATK_2",
  YOUTUBE = "KATK_3",
  JOIN_TELEGRAM_OFFICIAL_ANNOUNCEMENT = "KATK_4",
  JOIN_TELEGRAM_CHAT = "KATK_5",
  FOLLOW_TWITTER = "KATK_6",
  SHARE_LINKTREE = "KATK_7",
}
